{"version":3,"file":"circular-dependency.exception.js","sourceRoot":"/Users/hanxiaoxue/Documents/work/frontEndDebugger/nest/packages/core/","sources":["errors/exceptions/circular-dependency.exception.ts"],"names":[],"mappings":";;;AAAA,2DAAuD;AAEvD,MAAa,2BAA4B,SAAQ,oCAAgB;IAC/D,YAAY,OAAgB;QAC1B,MAAM,GAAG,GAAG,OAAO,CAAC,CAAC,CAAC,WAAW,OAAO,EAAE,CAAC,CAAC,CAAC,EAAE,CAAC;QAChD,KAAK,CACH,0CAA0C,GAAG,wGAAwG,CACtJ,CAAC;IACJ,CAAC;CACF;AAPD,kEAOC","sourcesContent":["import { RuntimeException } from './runtime.exception';\n\nexport class CircularDependencyException extends RuntimeException {\n  constructor(context?: string) {\n    const ctx = context ? ` inside ${context}` : ``;\n    super(\n      `A circular dependency has been detected${ctx}. Please, make sure that each side of a bidirectional relationships are decorated with \"forwardRef()\".`,\n    );\n  }\n}\n"]}